# Generated by Django 3.2.11 on 2022-04-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seedling_process_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_artichokes_seedlng_imgs', models.CharField(max_length=250)),
                ('good_seedling_quality_qty', models.CharField(max_length=250)),
                ('avrg_seedling_quality_qty', models.CharField(max_length=250)),
                ('bad_seedling_quality_qty', models.CharField(max_length=250)),
                ('good_seedling_quality_prcntg', models.CharField(max_length=250)),
                ('avrg_seedling_quality_prcntg', models.CharField(max_length=250)),
                ('bad_seedling_quality_prcntg', models.CharField(max_length=250)),
            ],
        ),
    ]
