# Generated by Django 3.2.11 on 2022-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedling_process_analysis',
            name='session_name',
            field=models.CharField(default='Test_session', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
