# Generated by Django 3.2.11 on 2022-04-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seedling_process_analysis_session_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_SPA_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_spa_session_name', models.CharField(default='Default_session', max_length=100, unique=True)),
            ],
        ),
    ]
