# Generated by Django 3.2.11 on 2022-04-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_current_spa_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_spa_session',
            name='id',
        ),
        migrations.AddField(
            model_name='current_spa_session',
            name='id_field',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
