# Generated by Django 3.2.11 on 2022-04-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220419_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedling_process_analysis',
            name='avrg_seedling_quality_prcntg',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seedling_process_analysis',
            name='avrg_seedling_quality_qty',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seedling_process_analysis',
            name='bad_seedling_quality_prcntg',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seedling_process_analysis',
            name='bad_seedling_quality_qty',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seedling_process_analysis',
            name='good_seedling_quality_prcntg',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seedling_process_analysis',
            name='good_seedling_quality_qty',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seedling_process_analysis',
            name='tot_artichokes_seedlng_imgs',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
