# Generated by Django 3.2.11 on 2022-04-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220420_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='seedling_img_samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=50, unique=True)),
                ('img_datetime', models.DateTimeField(auto_now_add=True)),
                ('num_seedling_objs', models.IntegerField(default=0)),
                ('spa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seedling_process_analysis')),
            ],
        ),
    ]
